In [1]:
import torch
import torch.nn.functional as F

In [8]:
# parameters
IMG_H = 3
IMG_W = 3
KER_H = 2
KER_W = 2
IN_CHANNELS = 1
OUT_CHANNELS = 1 
BATCH_SIZE = 1

In [9]:
torch.manual_seed(0)
inp = torch.randint(10, (BATCH_SIZE, IN_CHANNELS, IMG_H, IMG_W))
kernel = torch.ones(size=(BATCH_SIZE, OUT_CHANNELS, KER_H, KER_W)).type(torch.long)
print("Input:")
print(inp)
print("Kernel:")
print(kernel)

Input:
tensor([[[[4, 9, 3],
          [0, 3, 9],
          [7, 3, 7]]]])
Kernel:
tensor([[[[1, 1],
          [1, 1]]]])


In [10]:
torch.manual_seed(0)
inp = torch.randint(10, (BATCH_SIZE, IN_CHANNELS, 3, 3))
kernel = torch.ones(size=(BATCH_SIZE, OUT_CHANNELS, 2, 2)).type(torch.long)

In [16]:
padding = 0
stride = 1
F.conv_transpose2d(inp, kernel, stride=stride, padding=padding)

tensor([[[[ 4, 13, 12,  3],
          [ 4, 16, 24, 12],
          [ 7, 13, 22, 16],
          [ 7, 10, 10,  7]]]])

In [18]:
padding = 1
stride = 1
F.conv_transpose2d(inp, kernel, stride=stride, padding=padding)

tensor([[[[16, 24],
          [13, 22]]]])